### ISSUE TITLE
404 error and processing never stops

### ISSUE THREAD

**Issue by Fanarito** [egoist/vuepack-cli#1]
When I try to init a new project get processing thing then 404 error pops up, then nothing happens.

**Comment by egoist** [comment]
I'm ok with version 0.1.5, can you show me how you run into the bug?

**Comment by Fanarito** [comment]
On version 0.1.21 when I init a project like so `vue init HelloWorld` I get a 404 error and then vuepack just keeps processing.
Will upgrade to 0.1.5, to see if that fixes it.

**Comment by Fanarito** [comment]
Updating vuepack worked.
